/**
 * The question bank.
 *
 * Two populations. Diagnostic items (`d*`) are not attached to any lesson and
 * exist to place a new learner: three per track, spanning easy, medium and hard,
 * so twelve answers are enough to separate someone who knows the material from
 * someone who has heard the words. Practice items (`b*`, `c*`, `i*`, `t*`) are
 * attached to lessons and drilled after the reading.
 *
 * Difficulty is hand-assigned on a 0-1 scale and feeds the slip/guess adjustment
 * in mastery.ts. It is a judgement, not a calibration against response data — a
 * real deployment would fit these from usage, which is noted in the README as a
 * known limitation.
 */
import type { Item } from "./types";

export const DIAGNOSTIC_ITEMS: Item[] = [
  {
    id: "d-b1",
    skill: "budgeting",
    difficulty: 0.2,
    prompt: "Your net pay is $3,200 a month and your fixed bills come to $2,100. What is your discretionary cash flow?",
    choices: ["$3,200", "$2,100", "$1,100", "It depends on your gross pay"],
    answer: 2,
    explanation: "Discretionary cash flow is what remains after the bills that arrive regardless: $3,200 − $2,100 = $1,100. Gross pay is not part of the calculation.",
    lessons: [],
  },
  {
    id: "d-b2",
    skill: "budgeting",
    difficulty: 0.5,
    prompt: "Your essential outgoings are $2,600 a month and you earn $5,000 net. A three-month emergency fund should target roughly:",
    choices: ["$7,800", "$15,000", "$9,000", "$5,200"],
    answer: 0,
    explanation: "Emergency funds are sized against expenses, not income. Three months of $2,600 is $7,800. Sizing against the $5,000 salary would inflate the target by nearly double.",
    lessons: [],
  },
  {
    id: "d-b3",
    skill: "budgeting",
    difficulty: 0.8,
    prompt: "You get a $500/month raise and immediately move to an apartment costing $450 more. Your savings rate:",
    choices: [
      "Rises, because income rose",
      "Is essentially unchanged, and will fall as a share of income",
      "Falls in dollar terms",
      "Cannot be determined without knowing the tax rate",
    ],
    answer: 1,
    explanation: "Dollar savings barely move while income rose, so savings as a share of income drops. This is lifestyle creep: the raise was absorbed before it reached a savings line.",
    lessons: [],
  },
  {
    id: "d-c1",
    skill: "credit",
    difficulty: 0.25,
    prompt: "Which factor carries the most weight in a standard credit score?",
    choices: ["Length of credit history", "Payment history", "Credit mix", "Number of recent applications"],
    answer: 1,
    explanation: "Payment history is the single largest input, followed by amounts owed relative to limits. Mix and recent applications matter far less.",
    lessons: [],
  },
  {
    id: "d-c2",
    skill: "credit",
    difficulty: 0.55,
    prompt: "You have $1,200 across cards with $4,000 of total limit, and you pay in full every month. Your reported utilisation is likely to be:",
    choices: ["0%, because you pay in full", "30%, if that balance is showing at statement close", "12%", "Unreportable"],
    answer: 1,
    explanation: "Utilisation is captured when the issuer reports, usually at statement close, not at the due date. Paying in full afterwards does not change what was reported.",
    lessons: [],
  },
  {
    id: "d-c3",
    skill: "credit",
    difficulty: 0.85,
    prompt: "Debt A: $8,000 at 6%. Debt B: $1,500 at 23%. You have spare cash after minimums. The avalanche method directs it at:",
    choices: ["Debt A, because the balance is larger", "Debt B, because the rate is higher", "Split evenly", "Whichever has the longer term"],
    answer: 1,
    explanation: "Avalanche always targets the highest rate first, regardless of balance size. That ordering minimises total interest paid. Snowball would target B here too, but only because it happens to be smaller.",
    lessons: [],
  },
  {
    id: "d-i1",
    skill: "investing",
    difficulty: 0.2,
    prompt: "Compounding means:",
    choices: [
      "Returns are earned on prior returns as well as on the original amount",
      "Returns are guaranteed if you hold long enough",
      "Fees are charged annually",
      "Losses are offset against gains",
    ],
    answer: 0,
    explanation: "Compounding is growth on growth. It makes outcomes non-linear in time, which is why the first decade of investing matters more than the last.",
    lessons: [],
  },
  {
    id: "d-i2",
    skill: "investing",
    difficulty: 0.5,
    prompt: "Which portfolio is genuinely diversified?",
    choices: [
      "Ten large technology stocks",
      "Three funds all tracking the S&P 500",
      "A broad global equity fund plus a bond fund",
      "Five stocks, each the leader in its own technology niche",
    ],
    answer: 2,
    explanation: "Diversification requires holdings that do not move together. Ten tech stocks share sector shocks; three S&P trackers are the same bet three times.",
    lessons: [],
  },
  {
    id: "d-i3",
    skill: "investing",
    difficulty: 0.75,
    prompt: "Over 30 years at a 7% return, roughly how much of the ending balance does a 1% annual fee consume compared with a 0.05% fee?",
    choices: ["About 1%", "About 5%", "About a fifth", "About half"],
    answer: 2,
    explanation: "The fee is charged on the whole balance every year, so it takes the fee and all the growth that fee would have produced. Over three decades that compounds to roughly a fifth of the ending balance.",
    lessons: [],
  },
  {
    id: "d-t1",
    skill: "taxes",
    difficulty: 0.3,
    prompt: "You get a raise that pushes part of your income into a higher tax bracket. Your take-home pay:",
    choices: [
      "Falls, because the whole income is now taxed higher",
      "Rises, because only the income above the threshold is taxed at the higher rate",
      "Stays the same",
      "Depends on whether you itemise",
    ],
    answer: 1,
    explanation: "Brackets are marginal. Only the dollars above the threshold are taxed at the higher rate; everything below keeps its original rate. A raise cannot reduce take-home through brackets alone.",
    lessons: [],
  },
  {
    id: "d-t2",
    skill: "taxes",
    difficulty: 0.55,
    prompt: "A $1,000 tax credit and a $1,000 tax deduction at a 22% marginal rate are worth, respectively:",
    choices: ["$1,000 and $1,000", "$220 and $1,000", "$1,000 and $220", "$780 and $220"],
    answer: 2,
    explanation: "A credit reduces the tax itself, dollar for dollar. A deduction reduces taxable income, so it is worth your marginal rate: 22% of $1,000 is $220.",
    lessons: [],
  },
  {
    id: "d-t3",
    skill: "taxes",
    difficulty: 0.8,
    prompt: "You are early in your career at a low marginal rate and expect to earn substantially more later. All else equal, which contribution is usually favourable?",
    choices: [
      "Traditional, because the deduction is worth more now",
      "Roth, because you are paying tax at a rate you are unlikely to see again",
      "Neither, they are mathematically identical",
      "Whichever has the lower fees",
    ],
    answer: 1,
    explanation: "The comparison is your marginal rate now against your expected rate at withdrawal. At a low current rate, paying tax now and withdrawing free later usually wins. An employer match still outranks both.",
    lessons: [],
  },
];

export const PRACTICE_ITEMS: Item[] = [
  // Budgeting -------------------------------------------------------------
  {
    id: "b1",
    skill: "budgeting",
    difficulty: 0.2,
    prompt: "Which of these is an irregular cost rather than a fixed or variable one?",
    choices: ["Rent", "Groceries", "Annual car registration", "Streaming subscription"],
    answer: 2,
    explanation: "Irregular costs arrive annually or unpredictably. Dividing the annual total by twelve turns the March surprise into a monthly line.",
    lessons: ["cash-flow"],
  },
  {
    id: "b2",
    skill: "budgeting",
    difficulty: 0.4,
    prompt: "An annual insurance premium of $1,080 should appear in a monthly budget as:",
    choices: ["$1,080 in the month it is due", "$90 every month", "Nothing, it is not monthly", "$540 twice a year"],
    answer: 1,
    explanation: "$1,080 ÷ 12 = $90. Treating it as a monthly line means the money is already set aside when the bill lands.",
    lessons: ["cash-flow"],
  },
  {
    id: "b3",
    skill: "budgeting",
    difficulty: 0.3,
    prompt: "Under a 50/30/20 split on $4,000 net pay, the savings and debt line is:",
    choices: ["$400", "$800", "$1,200", "$2,000"],
    answer: 1,
    explanation: "20% of $4,000 is $800. The value of the framework is that this line exists before discretionary spending is decided, not after.",
    lessons: ["budget-frameworks"],
  },
  {
    id: "b4",
    skill: "budgeting",
    difficulty: 0.7,
    prompt: "Your needs alone consume 62% of net pay because of housing costs. The most useful response is:",
    choices: [
      "Force the 50/30/20 split anyway and run a deficit on paper",
      "Abandon budgeting frameworks entirely",
      "Keep the ordering — savings as a bill — and adjust the proportions to something achievable",
      "Move the shortfall onto a credit card each month",
    ],
    answer: 2,
    explanation: "The framework's value is the ordering, not the exact percentages. A budget you meet most months beats a stricter one abandoned in week three.",
    lessons: ["budget-frameworks"],
  },
  {
    id: "b5",
    skill: "budgeting",
    difficulty: 0.35,
    prompt: "Emergency funds are sized against:",
    choices: ["Monthly gross income", "Monthly net income", "Essential monthly expenses", "Total annual salary"],
    answer: 2,
    explanation: "The fund replaces what you must spend, not what you used to earn. Sizing against income inflates the target and makes it feel unreachable.",
    lessons: ["emergency-fund"],
  },
  {
    id: "b6",
    skill: "budgeting",
    difficulty: 0.65,
    prompt: "Who has the strongest case for a six-month rather than three-month cushion?",
    choices: [
      "A salaried nurse in a city with constant hiring",
      "A freelance contractor who is the sole earner in the household",
      "A graduate with low fixed costs living with family",
      "Two salaried earners in different industries",
    ],
    answer: 1,
    explanation: "Cushion size tracks how quickly income could be replaced. Lumpy contract income plus a single earner is the thinnest safety margin of the four.",
    lessons: ["emergency-fund"],
  },
  {
    id: "b7",
    skill: "budgeting",
    difficulty: 0.5,
    prompt: "What distinguishes a sinking fund from an emergency fund?",
    choices: [
      "A sinking fund is for expenses you already know are coming",
      "A sinking fund must be held in a separate account",
      "A sinking fund earns interest and an emergency fund does not",
      "There is no meaningful difference",
    ],
    answer: 0,
    explanation: "Sinking funds target known future costs; emergency funds cover the unknown. When the emergency fund pays for Christmas, it is not an emergency fund.",
    lessons: ["sinking-funds"],
  },
  {
    id: "b8",
    skill: "budgeting",
    difficulty: 0.6,
    prompt: "The mechanical defence against lifestyle creep is to:",
    choices: [
      "Track every transaction in a spreadsheet",
      "Route a fixed share of each raise into savings before it reaches a spending account",
      "Avoid raises until you have a budget",
      "Cancel all subscriptions annually",
    ],
    answer: 1,
    explanation: "Creep happens because spending is the default. Pre-committing part of the raise means the new money never establishes a new baseline.",
    lessons: ["lifestyle-creep"],
  },

  // Credit ----------------------------------------------------------------
  {
    id: "c1",
    skill: "credit",
    difficulty: 0.45,
    prompt: "A card quoted at 24% APR charges interest:",
    choices: [
      "Once a year, at 24% of the balance",
      "Monthly, at 2% with no compounding",
      "Daily, at a daily periodic rate that compounds",
      "Only on purchases over a threshold",
    ],
    answer: 2,
    explanation: "APR converts to a daily rate applied to the balance and compounded, so the effective annual cost exceeds the quoted 24%.",
    lessons: ["interest-basics"],
  },
  {
    id: "c2",
    skill: "credit",
    difficulty: 0.6,
    prompt: "Paying only the minimum on a $4,000 balance at 24% APR is likely to cost:",
    choices: [
      "A few hundred dollars over two years",
      "More than the original balance, over more than a decade",
      "Nothing extra, as long as the minimum is met",
      "Exactly 24% of $4,000, once",
    ],
    answer: 1,
    explanation: "Minimums are set so the balance falls very slowly. The number that matters is total paid over the life of the balance, not the monthly figure.",
    lessons: ["interest-basics"],
  },
  {
    id: "c3",
    skill: "credit",
    difficulty: 0.3,
    prompt: "Which two inputs account for the large majority of a credit score?",
    choices: [
      "Credit mix and recent applications",
      "Payment history and amounts owed relative to limits",
      "Length of history and credit mix",
      "Income and employment length",
    ],
    answer: 1,
    explanation: "Payment history and utilisation dominate. Income is not an input to the score at all, though lenders consider it separately.",
    lessons: ["credit-scores"],
  },
  {
    id: "c4",
    skill: "credit",
    difficulty: 0.7,
    prompt: "To lower the utilisation figure that gets reported, the effective move is to pay down:",
    choices: ["By the due date", "Before the statement closes", "On the first of the month", "In two installments"],
    answer: 1,
    explanation: "Issuers report at statement close. Paying by the due date clears the balance but after the snapshot was already taken.",
    lessons: ["credit-scores"],
  },
  {
    id: "c5",
    skill: "credit",
    difficulty: 0.4,
    prompt: "The avalanche method orders debts by:",
    choices: ["Smallest balance first", "Highest interest rate first", "Shortest remaining term first", "Oldest account first"],
    answer: 1,
    explanation: "Avalanche targets the highest rate, which always minimises total interest. Snowball targets the smallest balance for motivational reasons.",
    lessons: ["debt-payoff"],
  },
  {
    id: "c6",
    skill: "credit",
    difficulty: 0.75,
    prompt: "When is the snowball method most defensible over avalanche?",
    choices: [
      "When one debt is at 26% and another at 5%",
      "When the rates across debts are close together",
      "When total debt is very large",
      "Never — avalanche is always better",
    ],
    answer: 1,
    explanation: "With a small rate gap the extra interest cost of snowball is minor, so the higher completion rate dominates. With a 21-point gap, the cost of patience is worth paying.",
    lessons: ["debt-payoff"],
  },
  {
    id: "c7",
    skill: "credit",
    difficulty: 0.5,
    prompt: "Secured debt carries a lower rate than unsecured debt because:",
    choices: [
      "Secured lenders are regulated more tightly",
      "The lender can recover an asset if the borrower defaults",
      "Secured loans are always shorter",
      "Borrowers with collateral have higher incomes",
    ],
    answer: 1,
    explanation: "Collateral prices the risk. It also means consolidating unsecured debt onto secured borrowing changes what happens if you cannot pay.",
    lessons: ["secured-vs-unsecured"],
  },
  {
    id: "c8",
    skill: "credit",
    difficulty: 0.8,
    prompt: "Under a deferred-interest promotion, missing the payoff deadline by one dollar means:",
    choices: [
      "You owe interest on the remaining dollar only",
      "The promotion extends automatically",
      "All interest accrued since day one is charged retroactively",
      "The rate resets to the promotional rate",
    ],
    answer: 2,
    explanation: "Deferred interest accrues from the start and is waived only on full payoff by the deadline. True 0% APR never charged it. The distinction lives in the terms, not the advertising.",
    lessons: ["credit-products"],
  },

  // Investing -------------------------------------------------------------
  {
    id: "i1",
    skill: "investing",
    difficulty: 0.3,
    prompt: "Why does doubling the years invested more than double the result?",
    choices: [
      "Because contribution limits rise with age",
      "Because returns are earned on prior returns, making growth non-linear in time",
      "Because fees fall over time",
      "Because markets trend upward in later decades",
    ],
    answer: 1,
    explanation: "Growth on growth. This is the reason the same total contributed early beats a larger total contributed late.",
    lessons: ["compounding"],
  },
  {
    id: "i2",
    skill: "investing",
    difficulty: 0.7,
    prompt: "Investor A puts in $300/month from 25 to 35 and stops. Investor B puts in $300/month from 35 to 65. At 7%, who typically ends with more?",
    choices: ["B, having contributed three times as much", "A, because the early money compounds for thirty extra years", "They end level", "Cannot be compared"],
    answer: 1,
    explanation: "A contributes $36,000 and B contributes $108,000, yet A usually finishes ahead. The intuition that total contributions dominate is wrong over long horizons.",
    lessons: ["compounding"],
  },
  {
    id: "i3",
    skill: "investing",
    difficulty: 0.4,
    prompt: "In investing, 'risk' most commonly refers to:",
    choices: ["The chance of total loss", "Volatility, how much value swings around its trend", "Fraud exposure", "Inflation"],
    answer: 1,
    explanation: "Volatility is the price paid for expected return, not a defect to be engineered away. Investors are compensated for holding assets that bounce around.",
    lessons: ["risk-return"],
  },
  {
    id: "i4",
    skill: "investing",
    difficulty: 0.55,
    prompt: "You need a specific sum in 18 months for a down payment. That money belongs in:",
    choices: [
      "A broad equity fund, for the expected return",
      "Something stable, because the horizon is too short to absorb volatility",
      "A single stock with strong fundamentals",
      "Whatever matches your general risk tolerance",
    ],
    answer: 1,
    explanation: "The question is never risk tolerance in the abstract but when you need this particular money. Eighteen months does not give a drawdown time to recover.",
    lessons: ["risk-return"],
  },
  {
    id: "i5",
    skill: "investing",
    difficulty: 0.45,
    prompt: "Diversification is unusual among risk reductions because it:",
    choices: [
      "Guarantees a positive return",
      "Reduces volatility without lowering expected return",
      "Eliminates all risk",
      "Reduces fees",
    ],
    answer: 1,
    explanation: "Almost every other risk reduction costs return. Diversification works because idiosyncratic swings partly cancel, leaving expected return intact.",
    lessons: ["diversification"],
  },
  {
    id: "i6",
    skill: "investing",
    difficulty: 0.6,
    prompt: "Holding ten stocks all in one sector is closer to:",
    choices: ["Ten independent bets", "One bet", "A bond portfolio", "An index fund"],
    answer: 1,
    explanation: "They share sector shocks, so their prices move together. Real diversification varies asset class, sector and geography.",
    lessons: ["diversification"],
  },
  {
    id: "i7",
    skill: "investing",
    difficulty: 0.65,
    prompt: "Why does a 1% annual fee cost far more than 1% of the final balance?",
    choices: [
      "Because it is charged on contributions as well",
      "Because it is charged on the whole balance annually, taking the growth that money would have produced",
      "Because fees rise with the balance",
      "Because it is charged before tax",
    ],
    answer: 1,
    explanation: "The fee compounds against you exactly as returns compound for you. Over 30 years at 7% this is roughly a fifth of the ending balance.",
    lessons: ["fees"],
  },
  {
    id: "i8",
    skill: "investing",
    difficulty: 0.7,
    prompt: "The core argument for index funds rests on:",
    choices: [
      "Index funds cannot lose money",
      "Diversification in a single purchase, at very low cost",
      "Index funds outperform in every decade",
      "Active managers have no skill",
    ],
    answer: 1,
    explanation: "Two properties, together. The evidence is that most active funds trail their benchmark after fees, and the winners are not reliably the same ones next decade.",
    lessons: ["index-investing"],
  },

  // Taxes -----------------------------------------------------------------
  {
    id: "t1",
    skill: "taxes",
    difficulty: 0.25,
    prompt: "Income tax brackets are applied:",
    choices: [
      "To your whole income at the highest applicable rate",
      "In slices, with each slice taxed at its own rate",
      "Only to income above the standard deduction, at one flat rate",
      "Differently each quarter",
    ],
    answer: 1,
    explanation: "Brackets are marginal. Crossing a threshold taxes only the dollars above it at the higher rate.",
    lessons: ["brackets"],
  },
  {
    id: "t2",
    skill: "taxes",
    difficulty: 0.6,
    prompt: "Which number tells you what one additional dollar of deduction is worth?",
    choices: ["Effective rate", "Marginal rate", "Average rate", "Withholding rate"],
    answer: 1,
    explanation: "Marginal rate prices the next dollar in or out. Effective rate describes what you actually paid overall. Swapping them causes most tax confusion.",
    lessons: ["brackets"],
  },
  {
    id: "t3",
    skill: "taxes",
    difficulty: 0.35,
    prompt: "A large tax refund means:",
    choices: [
      "You paid less tax than you owed",
      "You overpaid through the year via withholding",
      "You qualified for extra credits",
      "Your employer made an error",
    ],
    answer: 1,
    explanation: "The refund is the reconciliation of an estimate that was too high. It is your money coming back, not a bonus.",
    lessons: ["withholding"],
  },
  {
    id: "t4",
    skill: "taxes",
    difficulty: 0.7,
    prompt: "For someone carrying credit card debt at 24%, a $3,000 annual refund is:",
    choices: [
      "Neutral, since the money comes back",
      "Good, because it enforces saving",
      "Expensive, because roughly $250/month was unavailable while high-rate interest accrued",
      "Irrelevant to the debt",
    ],
    answer: 2,
    explanation: "Over-withholding lends money at 0% while paying 24% elsewhere. Adjusting withholding puts the cash in hand as it is earned.",
    lessons: ["withholding"],
  },
  {
    id: "t5",
    skill: "taxes",
    difficulty: 0.4,
    prompt: "A deduction reduces:",
    choices: ["The tax owed, dollar for dollar", "Taxable income", "Your marginal rate", "Withholding only"],
    answer: 1,
    explanation: "Deductions reduce the income the tax is calculated on, so they are worth your marginal rate. Credits reduce the tax itself.",
    lessons: ["deductions-credits"],
  },
  {
    id: "t6",
    skill: "taxes",
    difficulty: 0.55,
    prompt: "Most filers take the standard deduction, which means:",
    choices: [
      "Itemised deductions are illegal for them",
      "Many commonly cited deductions have no effect on their bill",
      "They pay a higher effective rate",
      "They cannot claim credits",
    ],
    answer: 1,
    explanation: "You take the larger of standard or itemised, not both. If the standard deduction is larger, an additional itemisable expense changes nothing.",
    lessons: ["deductions-credits"],
  },
  {
    id: "t7",
    skill: "taxes",
    difficulty: 0.6,
    prompt: "Your employer matches 50% on the first 6% of salary contributed. Relative to the Roth-versus-traditional question, capturing the full match is:",
    choices: [
      "Less important, since the tax treatment compounds",
      "Equally important",
      "More important, because it is an immediate 50% return on those contributions",
      "Only relevant above a certain income",
    ],
    answer: 2,
    explanation: "The match is a guaranteed return before the market does anything. Neither tax treatment comes close, so the match generally comes first.",
    lessons: ["tax-advantaged"],
  },
  {
    id: "t8",
    skill: "taxes",
    difficulty: 0.65,
    prompt: "You bought a fund and are up 30% at the eleven-month mark. Selling now versus in two months changes:",
    choices: [
      "Nothing, gains are gains",
      "The rate: short-term gains are taxed as ordinary income, long-term at lower rates",
      "Whether the gain is taxable at all",
      "Only the paperwork",
    ],
    answer: 1,
    explanation: "The one-year holding period is the line between ordinary-income rates and long-term capital gains rates. The gap often matters more than a few percent of price.",
    lessons: ["capital-gains"],
  },
];

export const ALL_ITEMS: Item[] = [...DIAGNOSTIC_ITEMS, ...PRACTICE_ITEMS];

export const ITEMS_BY_ID: ReadonlyMap<string, Item> = new Map(
  ALL_ITEMS.map((item) => [item.id, item]),
);

export function itemsForLesson(lessonId: string): Item[] {
  return PRACTICE_ITEMS.filter((item) => item.lessons.includes(lessonId));
}
